### ISSUE TITLE
rond des checkbox a agrandir

### ISSUE THREAD

**Issue by auraalex21** [yoann90/Todo#18]

**Comment by auraalex21** [comment]
## Rond des checkbox a modifier 
il faut donc retirer "flex: 0 0 20px" et add 
```css
.name-tache .todo {
    height: 30px;
    width: 33px;
    border-radius: 30px;
    margin-right: 15px;
    border: 2px solid #f55632;
    cursor: pointer;
}
```
